"""Relational storage (SQLite locally, Postgres in prod — see database.py) for user
accounts and extraction run history. ORM shapes live in models.py, persistence in
repositories/, engine wiring in database.py, transaction boundaries in session.py (and
their per-request FastAPI dependency in dependencies.py).

Public interface — everything else that needs this imports it from here rather than
reaching into .database/.models/.repositories directly."""

from app.postgresdb.database import PostgresDB
from app.postgresdb.dependencies import DbSession, get_db_session
from app.postgresdb.models import (
    Bill,
    Claim,
    ClaimCode,
    Encounter,
    ExtractionRun,
    ExtractionRunResult,
    Gender,
    Patient,
    PhysicianPatient,
    PhysicianProfile,
    PhysicianType,
    RemunerationType,
    User,
    UserRole,
)
from app.postgresdb.repositories import (
    BillInput,
    BillRepository,
    ClaimAlreadyBilledError,
    ClaimCodeInput,
    ClaimContextInput,
    ClaimDetail,
    ClaimInput,
    ClaimRepository,
    ClaimWithCodes,
    DuplicateEncounterError,
    DuplicatePatientRamqNumberError,
    DuplicatePracticeNumberError,
    DuplicateRosterEntryError,
    EncounterActivity,
    EncounterInput,
    EncounterRepository,
    ExtractionAlreadyClaimedError,
    ExtractionRepository,
    ExtractionRunInput,
    ExtractionStageInput,
    PatientRepository,
    PhysicianPatientRepository,
    PhysicianProfileRepository,
    UserRepository,
)
from app.postgresdb.session import DatabaseNotOpenError, bind_database, session_scope

__all__ = [
    "PostgresDB",
    "DatabaseNotOpenError",
    "bind_database",
    "session_scope",
    "DbSession",
    "get_db_session",
    "Bill",
    "Claim",
    "ClaimCode",
    "Encounter",
    "ExtractionRun",
    "ExtractionRunResult",
    "Gender",
    "Patient",
    "PhysicianPatient",
    "PhysicianProfile",
    "PhysicianType",
    "RemunerationType",
    "User",
    "UserRole",
    "BillInput",
    "BillRepository",
    "ClaimAlreadyBilledError",
    "ClaimCodeInput",
    "ClaimContextInput",
    "ClaimDetail",
    "ClaimInput",
    "ClaimRepository",
    "ClaimWithCodes",
    "DuplicateEncounterError",
    "DuplicatePatientRamqNumberError",
    "DuplicatePracticeNumberError",
    "DuplicateRosterEntryError",
    "EncounterActivity",
    "EncounterInput",
    "EncounterRepository",
    "ExtractionAlreadyClaimedError",
    "ExtractionRepository",
    "ExtractionRunInput",
    "ExtractionStageInput",
    "PatientRepository",
    "PhysicianPatientRepository",
    "PhysicianProfileRepository",
    "UserRepository",
]
